
# for flashing : press boot button for 2-3 seconds before the serial connection initialize
# After OTA update, the EN (reset) button must be pressed to run firmware
# do not use gpio12 (MTDI)


############## General configuration

substitutions:
  name: floor-heating-og
  friendly_name: "Floor heating OG"
  revision: "1.108"

  #board and compilation
  board: nodemcu-32s
  framework: esp-idf #arduino

  #time
  TZ: "Europe/Berlin" #timezone
  reboot_days_of_week: "MON"
  reboot_hours: "5"
  reboot_minutes: "0"
  reboot_seconds: "0"
  # valve_maintenance_interval: "7days"
  onboot_valve_calibration_delay: "1min"


web_server:
  port: 80
  # log: false

# Enable Home Assistant API
api:
#  reboot_timeout: 30min


############## Channels definition (packages as template : https://esphome.io/guides/configuration-types.html#packages-as-templates)
packages:

##### test PID config
  # channel_1: !include
    # file: heating_channel_PID.yaml
    # vars:
      # channel_number: 1
      # id: wc #bad
      # frendly_name: wc #bad
      # temperature_sensor: corridor_temperature_sensor #ATC_51C199_Temperature
      # default_target_temperature: "21 °C"
      # pid_kp: "0.06"
      # pid_ki: "0.00011"
      # pid_kd: "4.0"
      # visual_min_temperature: "10 °C"
      # visual_max_temperature: "30 °C"
      # visual_temperature_step: "0.1 °C"
      # check_interval: "15min"
      # bemf_trigger_initial_value: "0.105"
      ### do not change :
      # bemf_sensor_adc: BEMF_1_2_sensor_ADC
      # bemf_linked_with_channel: 2
      # sn74hc595_IA_pin: 0
      # sn74hc595_IB_pin: 1

#### normal channel config
  channel_1: !include
    file: heating_channel.yaml
    vars:
      channel_number: 1
      id: bathroom_wall_heating
      frendly_name: Badezimmer Heizkörper
      temperature_sensor: pvvx_temperature_bathroom
      default_preset: home
      preset_1_name: home #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT_COOL #OFF, AUTO, HEAT, COOL, HEAT_COOL, FAN_ONLY, DRY
      preset_1_target_temperature_low: "19 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      preset_1_target_temperature_high: "20 °C"
      preset_2_name: away
      preset_2_mode: HEAT_COOL
      preset_2_target_temperature_low: "18 °C"
      preset_2_target_temperature_high: "19 °C"
      preset_3_name: boost
      preset_3_mode: HEAT_COOL
      preset_3_target_temperature_low: "23 °C"
      preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "17 °C"
      visual_max_temperature: "24 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "1min"
      bemf_trigger_initial_value: "0.105"
      # do not change :
      bemf_sensor_adc: BEMF_1_2_sensor_ADC
      bemf_linked_with_channel: 2
      sn74hc595_IA_pin: 0
      sn74hc595_IB_pin: 1

  channel_3: !include
    file: heating_channel.yaml
    vars:
      channel_number: 3
      id: rumpelkammer
      frendly_name: Rumpelkammer
      temperature_sensor: pvvx_temperature_rumpelkammer
      default_preset: home
      preset_1_name: home #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT_COOL #OFF, AUTO, HEAT, COOL, HEAT_COOL, FAN_ONLY, DRY
      preset_1_target_temperature_low: "21 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      preset_1_target_temperature_high: "23 °C"
      preset_2_name: away
      preset_2_mode: HEAT_COOL
      preset_2_target_temperature_low: "18 °C"
      preset_2_target_temperature_high: "19 °C"
      preset_3_name: boost
      preset_3_mode: HEAT_COOL
      preset_3_target_temperature_low: "23 °C"
      preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "17 °C"
      visual_max_temperature: "24 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "1min"
      bemf_trigger_initial_value: "0.105"
      ## do not change :
      bemf_sensor_adc: BEMF_3_4_sensor_ADC
      bemf_linked_with_channel: 4
      sn74hc595_IA_pin: 4
      sn74hc595_IB_pin: 5

  channel_5: !include
    file: heating_channel.yaml
    vars:
      channel_number: 5
      id: bathroom_floor_heating
      frendly_name: Badezimmer
      temperature_sensor: pvvx_temperature_bathroom
      default_preset: home
      preset_1_name: home #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT_COOL #OFF, AUTO, HEAT, COOL, HEAT_COOL, FAN_ONLY, DRY
      preset_1_target_temperature_low: "21 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      preset_1_target_temperature_high: "23 °C"
      preset_2_name: away
      preset_2_mode: HEAT_COOL
      preset_2_target_temperature_low: "18 °C"
      preset_2_target_temperature_high: "19 °C"
      preset_3_name: boost
      preset_3_mode: HEAT_COOL
      preset_3_target_temperature_low: "23 °C"
      preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "17 °C"
      visual_max_temperature: "24 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "1min"
      bemf_trigger_initial_value: "0.105"
      ## do not change :
      bemf_sensor_adc: BEMF_5_6_sensor_ADC
      bemf_linked_with_channel: 6
      sn74hc595_IA_pin: 8
      sn74hc595_IB_pin: 9

  channel_7: !include
    file: heating_channel.yaml
    vars:
      channel_number: 7
      id: bedroom
      frendly_name: Schlafzimmer
      temperature_sensor: pvvx_temperature_bedroom
      default_preset: home
      preset_1_name: home #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT_COOL #OFF, AUTO, HEAT, COOL, HEAT_COOL, FAN_ONLY, DRY
      preset_1_target_temperature_low: "17 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      preset_1_target_temperature_high: "18 °C"
      preset_2_name: away
      preset_2_mode: HEAT_COOL
      preset_2_target_temperature_low: "17 °C"
      preset_2_target_temperature_high: "18 °C"
      preset_3_name: boost
      preset_3_mode: HEAT_COOL
      preset_3_target_temperature_low: "23 °C"
      preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "17 °C"
      visual_max_temperature: "24 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "1min"
      bemf_trigger_initial_value: "0.105"
      ## do not change :
      bemf_sensor_adc: BEMF_7_8_sensor_ADC
      bemf_linked_with_channel: 8
      sn74hc595_IA_pin: 12
      sn74hc595_IB_pin: 13



  wifi: !include wifi.yaml
  board: !include board.yaml
  time: !include time.yaml
  #climate: !include climate.yaml
  #script_termostat_check: !include script_termostat_check.yaml
  script_calibrate_valves: !include script_calibrate_valves.yaml
  #switch_gpio: !include switch_gpio.yaml
  switch_others: !include switch_others.yaml
  inputs: !include inputs.yaml
  #covers: !include covers.yaml
  #sensor_bemf: !include sensor_bemf.yaml #back electromotive force (back EMF)
  sensor_adc: !include sensor_adc.yaml
  sensor_temperature: !include sensor_temperature.yaml
  sensor_others: !include sensor_others.yaml
