
sensor:



###### Other temperature sensor sample #######

  # - platform: dht
    # model : DHT22
    # pin: GPIO25
    # temperature:
      # name: "Switch Temperature"
      # id: switch_fan_controller_temperature
    # humidity:
      # name: "Switch Humidity"
      # id: switch_fan_controller_humidity
    # update_interval: 30s



  # - platform: xiaomi_lywsdcgq
    # mac_address: 58:2D:34:37:F1:10
    # temperature:
      # name: "Corridor Temperature"
      # id: xiaomi_corridor_temperature
    # humidity:
      # name: "Corridor Humidity"
      # id: xiaomi_corridor_humidity
    # battery_level:
      # name: "Corridor Xiaomi LYWSDCGQ Battery Level"
      # id: xiaomi_corridor_battery_level

  - platform: pvvx_mithermometer
    mac_address: "2D:34:11:EB:14:FF"
    temperature:
      name: "PVVX Temperature Livingroom Front"
      id: pvvx_temperature_livingroom_front
    humidity:
      name: "PVVX Humidity Livingroom Front"
    battery_level:
      name: "PVVX Battery-Level Livingroom Front"
    battery_voltage:
      name: "PVVX Battery-Voltage Livingroom Front"
    signal_strength:
      name: "PVVX Signal Livingroom Front"

  - platform: pvvx_mithermometer
    mac_address: "2D:34:11:EB:6A:FF"
    temperature:
      name: "PVVX Temperature Livingroom Back"
      id: pvvx_temperature_livingroom_back
    humidity:
      name: "PVVX Humidity Livingroom Back"
    battery_level:
      name: "PVVX Battery-Level Livingroom Back"
    battery_voltage:
      name: "PVVX Battery-Voltage Livingroom Back"
    signal_strength:
      name: "PVVX Signal Livingroom Back"

  - platform: pvvx_mithermometer
    mac_address: "2D:34:11:EB:52:FF"
    temperature:
      name: "PVVX Temperature Kitchen"
      id: pvvx_temperature_kitchen
    humidity:
      name: "PVVX Humidity Kitchen"
    battery_level:
      name: "PVVX Battery-Level Kitchen"
    battery_voltage:
      name: "PVVX Battery-Voltage Kitchen"
    signal_strength:
      name: "PVVX Signal Kitchen"

  - platform: pvvx_mithermometer
    mac_address: "2D:34:11:E1:C3:FF"
    temperature:
      name: "PVVX Temperature WC"
      id: pvvx_temperature_wc
    humidity:
      name: "PVVX Humidity WC"
    battery_level:
      name: "PVVX Battery-Level WC"
    battery_voltage:
      name: "PVVX Battery-Voltage WC"
    signal_strength:
      name: "PVVX Signal WC"

  - platform: pvvx_mithermometer
    mac_address: "2D:34:11:C9:B7:FF"
    temperature:
      name: "PVVX Temperature5"
      id: pvvx_temperature5
    humidity:
      name: "PVVX Humidity5"
    battery_level:
      name: "PVVX Battery-Level5"
    battery_voltage:
      name: "PVVX Battery-Voltage5"
    signal_strength:
      name: "PVVX Signal5"

# Connect 1-Wire bus with DS18B20 temperature sensors

# dallas:
  # - pin: GPI22
    # update_interval: 15s

# sensor:
  # - platform: dallas
    # address: 0x8b031760522cff28
    # name: "301_Heizkreis-WC-Vorlauf"
    # id: WC_Vorlauf
    # resolution: 12
    # accuracy_decimals: 2
    # filters:
      # - offset: 0.0

  # - platform: dallas
    # address: 0x353c38f649a51b28
    # name: "301_Heizkreis-WC-Ruecklauf"
    # id: WC_Ruecklauf
    # resolution: 12
    # accuracy_decimals: 2
    # filters:
      # - offset: 0.0